name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
        
      - name: Install
        run: npm install

      - name: Build
        run: |
          npm run build-css
          npm run build